/*
 * This file is generated by jOOQ.
 */
package com.tiemenv.digitalwallet.infrastructure.storage.jooq;


import com.tiemenv.digitalwallet.infrastructure.storage.jooq.tables.FlywaySchemaHistory;
import com.tiemenv.digitalwallet.infrastructure.storage.jooq.tables.Transactions;
import com.tiemenv.digitalwallet.infrastructure.storage.jooq.tables.Users;
import com.tiemenv.digitalwallet.infrastructure.storage.jooq.tables.Wallets;

import javax.annotation.processing.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FLYWAY_SCHEMA_HISTORY_PK = Indexes0.FLYWAY_SCHEMA_HISTORY_PK;
    public static final Index FLYWAY_SCHEMA_HISTORY_S_IDX = Indexes0.FLYWAY_SCHEMA_HISTORY_S_IDX;
    public static final Index IDX___TRANSACTIONS___ID = Indexes0.IDX___TRANSACTIONS___ID;
    public static final Index IDX___TRANSACTIONS___WALLET_ID = Indexes0.IDX___TRANSACTIONS___WALLET_ID;
    public static final Index PK___TRANSACTION_ID___ID = Indexes0.PK___TRANSACTION_ID___ID;
    public static final Index IDX___USERS___ID = Indexes0.IDX___USERS___ID;
    public static final Index PK___USER_ID___ID = Indexes0.PK___USER_ID___ID;
    public static final Index USERS_USERNAME_KEY = Indexes0.USERS_USERNAME_KEY;
    public static final Index IDX___WALLETS___ID = Indexes0.IDX___WALLETS___ID;
    public static final Index IDX___WALLETS___USER_ID = Indexes0.IDX___WALLETS___USER_ID;
    public static final Index PK___WALLET_ID___ID = Indexes0.PK___WALLET_ID___ID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index FLYWAY_SCHEMA_HISTORY_PK = Internal.createIndex("flyway_schema_history_pk", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
        public static Index FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex("flyway_schema_history_s_idx", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
        public static Index IDX___TRANSACTIONS___ID = Internal.createIndex("IDX___transactions___id", Transactions.TRANSACTIONS, new OrderField[] { Transactions.TRANSACTIONS.ID }, false);
        public static Index IDX___TRANSACTIONS___WALLET_ID = Internal.createIndex("IDX___transactions___wallet_id", Transactions.TRANSACTIONS, new OrderField[] { Transactions.TRANSACTIONS.WALLET_ID }, false);
        public static Index PK___TRANSACTION_ID___ID = Internal.createIndex("PK___transaction_id___id", Transactions.TRANSACTIONS, new OrderField[] { Transactions.TRANSACTIONS.ID }, true);
        public static Index IDX___USERS___ID = Internal.createIndex("IDX___users___id", Users.USERS, new OrderField[] { Users.USERS.ID }, false);
        public static Index PK___USER_ID___ID = Internal.createIndex("PK___user_id___id", Users.USERS, new OrderField[] { Users.USERS.ID }, true);
        public static Index USERS_USERNAME_KEY = Internal.createIndex("users_username_key", Users.USERS, new OrderField[] { Users.USERS.USERNAME }, true);
        public static Index IDX___WALLETS___ID = Internal.createIndex("IDX___wallets___id", Wallets.WALLETS, new OrderField[] { Wallets.WALLETS.ID }, false);
        public static Index IDX___WALLETS___USER_ID = Internal.createIndex("IDX___wallets___user_id", Wallets.WALLETS, new OrderField[] { Wallets.WALLETS.USER_ID }, false);
        public static Index PK___WALLET_ID___ID = Internal.createIndex("PK___wallet_id___id", Wallets.WALLETS, new OrderField[] { Wallets.WALLETS.ID }, true);
    }
}
