/*
 * This file is generated by jOOQ.
 */
package com.tiemenv.digitalwallet.infrastructure.storage.jooq;


import com.tiemenv.digitalwallet.infrastructure.storage.jooq.tables.FlywaySchemaHistory;
import com.tiemenv.digitalwallet.infrastructure.storage.jooq.tables.Transactions;
import com.tiemenv.digitalwallet.infrastructure.storage.jooq.tables.Users;
import com.tiemenv.digitalwallet.infrastructure.storage.jooq.tables.Wallets;
import com.tiemenv.digitalwallet.infrastructure.storage.jooq.tables.records.FlywaySchemaHistoryRecord;
import com.tiemenv.digitalwallet.infrastructure.storage.jooq.tables.records.TransactionsRecord;
import com.tiemenv.digitalwallet.infrastructure.storage.jooq.tables.records.UsersRecord;
import com.tiemenv.digitalwallet.infrastructure.storage.jooq.tables.records.WalletsRecord;

import javax.annotation.processing.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = UniqueKeys0.FLYWAY_SCHEMA_HISTORY_PK;
    public static final UniqueKey<TransactionsRecord> PK___TRANSACTION_ID___ID = UniqueKeys0.PK___TRANSACTION_ID___ID;
    public static final UniqueKey<UsersRecord> PK___USER_ID___ID = UniqueKeys0.PK___USER_ID___ID;
    public static final UniqueKey<UsersRecord> USERS_USERNAME_KEY = UniqueKeys0.USERS_USERNAME_KEY;
    public static final UniqueKey<WalletsRecord> PK___WALLET_ID___ID = UniqueKeys0.PK___WALLET_ID___ID;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<TransactionsRecord, WalletsRecord> TRANSACTIONS__FK___TRANSACTIONS___WALLET_ID = ForeignKeys0.TRANSACTIONS__FK___TRANSACTIONS___WALLET_ID;
    public static final ForeignKey<WalletsRecord, UsersRecord> WALLETS__FK___WALLETS___USER_ID = ForeignKeys0.WALLETS__FK___WALLETS___USER_ID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, "flyway_schema_history_pk", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK);
        public static final UniqueKey<TransactionsRecord> PK___TRANSACTION_ID___ID = Internal.createUniqueKey(Transactions.TRANSACTIONS, "PK___transaction_id___id", Transactions.TRANSACTIONS.ID);
        public static final UniqueKey<UsersRecord> PK___USER_ID___ID = Internal.createUniqueKey(Users.USERS, "PK___user_id___id", Users.USERS.ID);
        public static final UniqueKey<UsersRecord> USERS_USERNAME_KEY = Internal.createUniqueKey(Users.USERS, "users_username_key", Users.USERS.USERNAME);
        public static final UniqueKey<WalletsRecord> PK___WALLET_ID___ID = Internal.createUniqueKey(Wallets.WALLETS, "PK___wallet_id___id", Wallets.WALLETS.ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<TransactionsRecord, WalletsRecord> TRANSACTIONS__FK___TRANSACTIONS___WALLET_ID = Internal.createForeignKey(com.tiemenv.digitalwallet.infrastructure.storage.jooq.Keys.PK___WALLET_ID___ID, Transactions.TRANSACTIONS, "transactions__FK___transactions___wallet_id", Transactions.TRANSACTIONS.WALLET_ID);
        public static final ForeignKey<WalletsRecord, UsersRecord> WALLETS__FK___WALLETS___USER_ID = Internal.createForeignKey(com.tiemenv.digitalwallet.infrastructure.storage.jooq.Keys.PK___USER_ID___ID, Wallets.WALLETS, "wallets__FK___wallets___user_id", Wallets.WALLETS.USER_ID);
    }
}
