/*
 * This file is generated by jOOQ.
 */
package com.tiemenv.digitalwallet.infrastructure.storage.jooq;


import com.tiemenv.digitalwallet.infrastructure.storage.jooq.tables.FlywaySchemaHistory;
import com.tiemenv.digitalwallet.infrastructure.storage.jooq.tables.Transactions;
import com.tiemenv.digitalwallet.infrastructure.storage.jooq.tables.Users;
import com.tiemenv.digitalwallet.infrastructure.storage.jooq.tables.Wallets;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.transactions</code>.
     */
    public static final Transactions TRANSACTIONS = Transactions.TRANSACTIONS;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;

    /**
     * The table <code>public.wallets</code>.
     */
    public static final Wallets WALLETS = Wallets.WALLETS;
}
