/*
 * This file is generated by jOOQ.
 */
package com.tiemenv.digitalwallet.infrastructure.storage.jooq.tables.records;


import com.tiemenv.digitalwallet.infrastructure.storage.jooq.enums.Currency;
import com.tiemenv.digitalwallet.infrastructure.storage.jooq.tables.Wallets;

import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WalletsRecord extends UpdatableRecordImpl<WalletsRecord> implements Record6<UUID, UUID, Double, Currency, Boolean, Timestamp> {

    private static final long serialVersionUID = 1219283528;

    /**
     * Setter for <code>public.wallets.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.wallets.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.wallets.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.wallets.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.wallets.balance</code>.
     */
    public void setBalance(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.wallets.balance</code>.
     */
    public Double getBalance() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>public.wallets.currency</code>.
     */
    public void setCurrency(Currency value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.wallets.currency</code>.
     */
    public Currency getCurrency() {
        return (Currency) get(3);
    }

    /**
     * Setter for <code>public.wallets.is_locked</code>.
     */
    public void setIsLocked(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.wallets.is_locked</code>.
     */
    public Boolean getIsLocked() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.wallets.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.wallets.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<UUID, UUID, Double, Currency, Boolean, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<UUID, UUID, Double, Currency, Boolean, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Wallets.WALLETS.ID;
    }

    @Override
    public Field<UUID> field2() {
        return Wallets.WALLETS.USER_ID;
    }

    @Override
    public Field<Double> field3() {
        return Wallets.WALLETS.BALANCE;
    }

    @Override
    public Field<Currency> field4() {
        return Wallets.WALLETS.CURRENCY;
    }

    @Override
    public Field<Boolean> field5() {
        return Wallets.WALLETS.IS_LOCKED;
    }

    @Override
    public Field<Timestamp> field6() {
        return Wallets.WALLETS.CREATED_AT;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getUserId();
    }

    @Override
    public Double component3() {
        return getBalance();
    }

    @Override
    public Currency component4() {
        return getCurrency();
    }

    @Override
    public Boolean component5() {
        return getIsLocked();
    }

    @Override
    public Timestamp component6() {
        return getCreatedAt();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getUserId();
    }

    @Override
    public Double value3() {
        return getBalance();
    }

    @Override
    public Currency value4() {
        return getCurrency();
    }

    @Override
    public Boolean value5() {
        return getIsLocked();
    }

    @Override
    public Timestamp value6() {
        return getCreatedAt();
    }

    @Override
    public WalletsRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public WalletsRecord value2(UUID value) {
        setUserId(value);
        return this;
    }

    @Override
    public WalletsRecord value3(Double value) {
        setBalance(value);
        return this;
    }

    @Override
    public WalletsRecord value4(Currency value) {
        setCurrency(value);
        return this;
    }

    @Override
    public WalletsRecord value5(Boolean value) {
        setIsLocked(value);
        return this;
    }

    @Override
    public WalletsRecord value6(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public WalletsRecord values(UUID value1, UUID value2, Double value3, Currency value4, Boolean value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WalletsRecord
     */
    public WalletsRecord() {
        super(Wallets.WALLETS);
    }

    /**
     * Create a detached, initialised WalletsRecord
     */
    public WalletsRecord(UUID id, UUID userId, Double balance, Currency currency, Boolean isLocked, Timestamp createdAt) {
        super(Wallets.WALLETS);

        set(0, id);
        set(1, userId);
        set(2, balance);
        set(3, currency);
        set(4, isLocked);
        set(5, createdAt);
    }
}
